// frontend/src/components/layout/AppSidebar.vue
<script setup>
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import { useChatStore } from '../../stores/chat'
import { useAppStore } from '../../stores/app'
import { GraduationCap, Plus, MessageCircle, User, BookOpen, GitBranch, Route, LogOut, Trash2 } from 'lucide-vue-next'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()
const chatStore = useChatStore()
const appStore = useAppStore()

const navItems = [
  { name: 'Chat', path: '/chat', label: '智能对话', icon: MessageCircle, color: 'text-[#4285f4]' },
  { name: 'Profile', path: '/profile', label: '学习画像', icon: User, color: 'text-[#ea4335]' },
  { name: 'Resources', path: '/resources', label: '学习资源', icon: BookOpen, color: 'text-[#34a853]' },
  { name: 'Mindmap', path: '/mindmap', label: '思维导图', icon: GitBranch, color: 'text-[#fbbc04]' },
  { name: 'Path', path: '/path', label: '学习路径', icon: Route, color: 'text-[#4285f4]' },
]

function navigateTo(path) {
  router.push(path)
  if (window.innerWidth < 768) {
    appStore.sidebarOpen = false
  }
}

function startNewChat() {
  chatStore.startNewChat()
  router.push('/chat')
}

function handleLogout() {
  if (chatStore.isStreaming) return
  authStore.logout()
  chatStore.startNewChat()
  chatStore.conversations = []
}

async function handleDeleteConversation(e, id) {
  e.stopPropagation()
  await chatStore.deleteConversation(id)
}
</script>

<template>
  <aside
    :class="[
      'w-64 flex flex-col flex-shrink-0 transition-all duration-200 z-40 border-r border-[#dadce0] bg-[#f8f9fa]',
      appStore.sidebarOpen ? 'translate-x-0' : '-translate-x-full absolute h-full',
    ]"
  >
    <!-- Brand -->
    <div class="p-4 flex items-center gap-3">
      <div class="w-9 h-9 rounded-lg bg-gradient-to-br from-[#4285f4] to-[#34a853] flex items-center justify-center shadow-sm">
        <GraduationCap class="w-5 h-5 text-white" />
      </div>
      <div>
        <h1 class="text-[#202124] font-semibold text-sm leading-tight">Python 学习助手</h1>
        <p class="text-[#9aa0a6] text-xs">软件杯 A3 赛题</p>
      </div>
    </div>

    <!-- New Chat -->
    <div class="px-3 mb-2">
      <button
        @click="startNewChat"
        class="w-full flex items-center gap-2 px-3 py-2.5 rounded-full border border-[#dadce0] text-[#1a73e8] hover:bg-[#e8f0fe] hover:border-[#a8c7fa] transition-all text-sm font-medium"
      >
        <Plus class="w-4 h-4" />
        <span>新建对话</span>
      </button>
    </div>

    <!-- Conversation List -->
    <div class="px-3 mb-3 overflow-y-auto" style="max-height: 35vh">
      <div
        v-for="conv in chatStore.conversations"
        :key="conv.id"
        @click="chatStore.switchConversation(conv.id); router.push('/chat')"
        :class="[
          'group flex items-center gap-2 px-3 py-2 rounded-full cursor-pointer transition-all text-sm mb-0.5',
          chatStore.currentConversationId === conv.id
            ? 'bg-[#e8f0fe] text-[#1a73e8] font-medium'
            : 'text-[#5f6368] hover:bg-[#f1f3f4] hover:text-[#202124]',
        ]"
      >
        <MessageCircle class="w-4 h-4 flex-shrink-0" />
        <span class="flex-1 truncate">{{ conv.title }}</span>
        <button
          @click="handleDeleteConversation($event, conv.id)"
          class="opacity-0 group-hover:opacity-100 text-[#9aa0a6] hover:text-[#ea4335] transition-all"
        >
          <Trash2 class="w-3.5 h-3.5" />
        </button>
      </div>
    </div>

    <!-- Divider -->
    <div class="mx-3 border-t border-[#e0e0e0]"></div>

    <!-- Navigation -->
    <nav class="flex-1 px-3 py-2 space-y-0.5 overflow-y-auto">
      <button
        v-for="item in navItems"
        :key="item.name"
        @click="navigateTo(item.path)"
        :class="[
          'w-full flex items-center gap-3 px-3 py-2.5 rounded-full text-sm transition-all',
          route.path === item.path
            ? 'bg-[#e8f0fe] text-[#1a73e8] font-medium'
            : 'text-[#5f6368] hover:bg-[#f1f3f4] hover:text-[#202124]',
        ]"
      >
        <component :is="item.icon" :class="['w-5 h-5', route.path === item.path ? 'text-[#1a73e8]' : item.color]" />
        <span>{{ item.label }}</span>
      </button>
    </nav>

    <!-- User Info -->
    <div class="p-3 border-t border-[#e0e0e0]">
      <div class="flex items-center gap-3 px-2">
        <div class="w-8 h-8 rounded-full bg-gradient-to-br from-[#4285f4] to-[#34a853] flex items-center justify-center">
          <User class="w-4 h-4 text-white" />
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-[#202124] text-sm font-medium truncate">{{ authStore.username || '学习者' }}</p>
          <p class="text-[#34a853] text-xs flex items-center gap-1">
            <span class="w-1.5 h-1.5 rounded-full bg-[#34a853] inline-block"></span>
            在线
          </p>
        </div>
        <button
          @click="handleLogout"
          class="text-[#9aa0a6] hover:text-[#ea4335] transition-colors p-1.5 rounded-full hover:bg-[#fce8e6]"
          title="退出登录"
        >
          <LogOut class="w-4 h-4" />
        </button>
      </div>
    </div>
  </aside>

  <!-- Mobile overlay -->
  <div
    v-if="appStore.sidebarOpen"
    @click="appStore.sidebarOpen = false"
    class="fixed inset-0 bg-black/30 z-30 md:hidden"
  />
</template>

// frontend/src/components/layout/AppSidebar.tsx
import React, { useCallback, useMemo } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useAuthStore } from '../../stores/auth'
import { useChatStore } from '../../stores/chat'
import { useAppStore } from '../../stores/app'
import { Plus, LogOut, Trash2 } from 'lucide-react'

// --- 类型定义 ---
interface NavItem {
  name: string
  path: string
  label: string
}

// --- 常量 ---
const NAV_ITEMS: NavItem[] = [
  { name: 'Chat', path: '/chat', label: '智能对话' },
  { name: 'Profile', path: '/profile', label: '学习画像' },
  { name: 'Resources', path: '/resources', label: '学习资源' },
  { name: 'Mindmap', path: '/mindmap', label: '思维导图' },
  { name: 'Path', path: '/path', label: '学习路径' },
  { name: 'ErrorBook', path: '/error-book', label: '错题本' },
  { name: 'Playground', path: '/playground', label: '代码练习' },
  { name: 'Animation', path: '/animation', label: '教学动画' },
]

// --- 组件 ---
const AppSidebar: React.FC = () => {
  const navigate = useNavigate()
  const location = useLocation()
  const authStore = useAuthStore()
  const chatStore = useChatStore()
  const appStore = useAppStore()

  // --- 导航 ---
  const navigateTo = useCallback((path: string) => {
    navigate(path)
    if (window.innerWidth < 768) {
      appStore.setSidebarOpen(false)
    }
  }, [navigate, appStore])

  // --- 新建对话 ---
  const startNewChat = useCallback(() => {
    chatStore.startNewChat()
    navigate('/chat')
  }, [chatStore, navigate])

  // --- 退出登录 ---
  const handleLogout = useCallback(() => {
    if (chatStore.isStreaming) return
    authStore.logout()
    chatStore.startNewChat()
  }, [authStore, chatStore])

  // --- 删除对话 ---
  const handleDeleteConversation = useCallback(async (e: React.MouseEvent, id: string | number) => {
    e.stopPropagation()
    if (!window.confirm('确定要删除这个对话吗？')) return
    await chatStore.deleteConversation(id)
  }, [chatStore])

  // --- 用户名首字母 ---
  const userInitial = useMemo(() => (authStore.username || '学')[0], [authStore.username])

  return (
    <>
      <aside
        className={`flex flex-col flex-shrink-0 transition-all duration-200 z-40 ${
          appStore.sidebarOpen ? 'translate-x-0' : '-translate-x-full absolute h-full'
        }`}
        style={{ width: 260, background: '#f9fafb' }}
      >
        {/* Brand */}
        <div style={{ padding: '16px 16px 12px' }}>
          <h1 style={{ fontSize: 15, fontWeight: 600, color: '#111827', margin: 0 }}>Python 学习助手</h1>
        </div>

        {/* New Chat */}
        <div style={{ padding: '0 12px 8px' }}>
          <button
            onClick={startNewChat}
            style={{
              width: '100%', display: 'flex', alignItems: 'center', gap: 8,
              padding: '8px 12px', background: '#ffffff', border: '1px solid #e5e7eb',
              borderRadius: 8, color: '#374151', fontSize: 14, cursor: 'pointer',
              transition: 'background 0.15s ease',
            }}
            onMouseEnter={e => (e.currentTarget.style.background = '#f3f4f6')}
            onMouseLeave={e => (e.currentTarget.style.background = '#ffffff')}
          >
            <Plus style={{ width: 16, height: 16 }} />
            <span>新建对话</span>
          </button>
        </div>

        {/* Conversation List */}
        <div style={{ padding: '0 12px', overflowY: 'auto', maxHeight: '35vh', display: 'flex', flexDirection: 'column', gap: 4 }}>
          {chatStore.conversations.map(conv => (
            <div
              key={conv.id}
              className="conv-item"
              onClick={() => { chatStore.switchConversation(conv.id); navigate('/chat') }}
              style={{
                padding: '8px 12px', borderRadius: 6, cursor: 'pointer', fontSize: 14,
                transition: 'background 0.15s ease', display: 'flex', alignItems: 'center', gap: 8,
                background: chatStore.currentConversationId === conv.id ? '#e5e7eb' : 'transparent',
                color: chatStore.currentConversationId === conv.id ? '#111827' : '#374151',
                fontWeight: chatStore.currentConversationId === conv.id ? 500 : 400,
              }}
              onMouseEnter={e => {
                if (chatStore.currentConversationId !== conv.id) {
                  (e.currentTarget as HTMLElement).style.background = '#f3f4f6'
                }
              }}
              onMouseLeave={e => {
                if (chatStore.currentConversationId !== conv.id) {
                  (e.currentTarget as HTMLElement).style.background = 'transparent'
                }
              }}
            >
              <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {conv.title}
              </span>
              <button
                onClick={e => handleDeleteConversation(e, conv.id)}
                className="conv-delete-btn"
                title="删除对话"
                style={{
                  background: 'none', border: 'none', color: '#9ca3af',
                  cursor: 'pointer', padding: 2, transition: 'color 0.15s',
                }}
                onMouseEnter={e => (e.currentTarget.style.color = '#ef4444')}
                onMouseLeave={e => (e.currentTarget.style.color = '#9ca3af')}
              >
                <Trash2 style={{ width: 12, height: 12 }} />
              </button>
            </div>
          ))}
        </div>

        {/* Divider */}
        <div style={{ margin: '8px 12px', borderTop: '1px solid #e5e7eb' }} />

        {/* Navigation */}
        <nav style={{ flex: 1, padding: '4px 12px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 2 }}>
          {NAV_ITEMS.map(item => (
            <button
              key={item.name}
              onClick={() => navigateTo(item.path)}
              style={{
                width: '100%', display: 'flex', alignItems: 'center',
                padding: '8px 12px', borderRadius: 6, fontSize: 14,
                border: 'none', cursor: 'pointer', transition: 'background 0.15s ease',
                height: 40,
                background: location.pathname === item.path ? '#e5e7eb' : 'transparent',
                color: location.pathname === item.path ? '#111827' : '#374151',
                fontWeight: location.pathname === item.path ? 500 : 400,
              }}
              onMouseEnter={e => {
                if (location.pathname !== item.path) {
                  (e.currentTarget as HTMLElement).style.background = '#f3f4f6'
                }
              }}
              onMouseLeave={e => {
                if (location.pathname !== item.path) {
                  (e.currentTarget as HTMLElement).style.background = 'transparent'
                }
              }}
            >
              <span>{item.label}</span>
            </button>
          ))}
        </nav>

        {/* User Info */}
        <div style={{ padding: 12, borderTop: '1px solid #e5e7eb' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '0 8px' }}>
            <div style={{
              width: 28, height: 28, borderRadius: '50%', background: '#10b981',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <span style={{ color: '#ffffff', fontSize: 12, fontWeight: 600 }}>{userInitial}</span>
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <p style={{
                fontSize: 14, fontWeight: 500, color: '#111827', margin: 0,
                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
              }}>
                {authStore.username || '学习者'}
              </p>
            </div>
            <button
              onClick={handleLogout}
              style={{ background: 'none', border: 'none', color: '#9ca3af', cursor: 'pointer', padding: 4, transition: 'color 0.15s' }}
              onMouseEnter={e => (e.currentTarget.style.color = '#374151')}
              onMouseLeave={e => (e.currentTarget.style.color = '#9ca3af')}
              title="退出登录"
            >
              <LogOut style={{ width: 16, height: 16 }} />
            </button>
          </div>
        </div>
      </aside>

      {/* Mobile overlay */}
      {appStore.sidebarOpen && (
        <div
          onClick={() => appStore.setSidebarOpen(false)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.3)', zIndex: 30 }}
          className="md:hidden"
        />
      )}

      {/* Scoped style for conversation delete button hover */}
      <style>{`
        .conv-delete-btn {
          visibility: hidden;
        }
        .conv-item:hover .conv-delete-btn {
          visibility: visible;
        }
      `}</style>
    </>
  )
}

export default AppSidebar
