// frontend/src/components/chat/ChatInput.tsx
import React, { useState, useRef, useCallback, useEffect, useImperativeHandle, forwardRef } from 'react'
import { Send, Square } from 'lucide-react'

// --- 类型定义 ---
interface ChatInputProps {
  isStreaming?: boolean
  placeholder?: string
  onSend: (text: string) => void
  onAbort: () => void
}

export interface ChatInputHandle {
  focus: () => void
}

// --- 常量 ---
const DEFAULT_PLACEHOLDER = '输入你的问题... (Shift+Enter 换行)'

// --- 组件 ---
const ChatInput = forwardRef<ChatInputHandle, ChatInputProps>(
  ({ isStreaming = false, placeholder = '', onSend, onAbort }, ref) => {
    const [message, setMessage] = useState('')
    const textareaRef = useRef<HTMLTextAreaElement>(null)

    const currentPlaceholder = placeholder || DEFAULT_PLACEHOLDER
    const trimmed = message.trim()

    // --- 暴露 focus 方法 ---
    useImperativeHandle(ref, () => ({
      focus: () => {
        requestAnimationFrame(() => textareaRef.current?.focus())
      }
    }), [])

    // --- 调整高度 ---
    const adjustHeight = useCallback(() => {
      const el = textareaRef.current
      if (!el) return
      el.style.height = 'auto'
      el.style.height = Math.min(el.scrollHeight, 128) + 'px'
    }, [])

    // --- 发送 ---
    const handleSend = useCallback(() => {
      const text = message.trim()
      if (!text || isStreaming) return
      onSend(text)
      setMessage('')
      requestAnimationFrame(adjustHeight)
    }, [message, isStreaming, onSend, adjustHeight])

    // --- 键盘事件 ---
    const handleKeydown = useCallback((e: React.KeyboardEvent) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        handleSend()
      }
    }, [handleSend])

    // placeholder 变化时同步高度
    useEffect(() => {
      adjustHeight()
    }, [placeholder, adjustHeight])

    return (
      <div style={{ padding: '16px 64px' }}>
        <div
          style={{
            background: '#f9fafb', border: '1px solid #e5e7eb',
            borderRadius: 12, padding: '12px 16px', transition: 'border-color 0.15s ease',
          }}
          onFocusCapture={e => {
            (e.currentTarget as HTMLElement).style.borderColor = '#10b981'
          }}
          onBlurCapture={e => {
            (e.currentTarget as HTMLElement).style.borderColor = '#e5e7eb'
          }}
        >
          <form
            onSubmit={e => { e.preventDefault(); handleSend() }}
            style={{ display: 'flex', alignItems: 'flex-end', gap: 12 }}
          >
            <textarea
              ref={textareaRef}
              value={message}
              onChange={e => setMessage(e.target.value)}
              onKeyDown={handleKeydown}
              onInput={adjustHeight}
              placeholder={currentPlaceholder}
              rows={1}
              style={{
                flex: 1, background: 'transparent', border: 'none', outline: 'none',
                resize: 'none', fontSize: 15, color: '#111827', lineHeight: 1.5,
                maxHeight: 128, minHeight: 24, fontFamily: 'inherit',
              }}
            />
            {isStreaming ? (
              <button
                type="button"
                onClick={onAbort}
                style={{
                  padding: '6px 14px', borderRadius: 8, border: 'none',
                  background: '#ef4444', color: '#ffffff', cursor: 'pointer',
                  transition: 'background 0.15s ease', display: 'flex', alignItems: 'center',
                }}
                onMouseEnter={e => (e.currentTarget.style.background = '#dc2626')}
                onMouseLeave={e => (e.currentTarget.style.background = '#ef4444')}
              >
                <Square style={{ width: 16, height: 16 }} />
              </button>
            ) : (
              <button
                type="submit"
                disabled={!trimmed}
                style={{
                  padding: '6px 14px', borderRadius: 8, border: 'none',
                  background: '#10b981', color: '#ffffff',
                  cursor: trimmed ? 'pointer' : 'not-allowed',
                  transition: 'background 0.15s ease', display: 'flex', alignItems: 'center',
                  opacity: trimmed ? 1 : 0.4,
                }}
                onMouseEnter={e => { if (trimmed) e.currentTarget.style.background = '#059669' }}
                onMouseLeave={e => (e.currentTarget.style.background = '#10b981')}
              >
                <Send style={{ width: 16, height: 16 }} />
              </button>
            )}
          </form>
        </div>
        <p style={{ fontSize: 12, color: '#9ca3af', margin: '8px 0 0', textAlign: 'center' }}>
          按 Enter 发送，Shift+Enter 换行
        </p>
      </div>
    )
  }
)

ChatInput.displayName = 'ChatInput'

export default ChatInput

// frontend/src/components/chat/ChatInput.vue
<script setup>
import { ref, nextTick } from 'vue'
import { Send, Square } from 'lucide-vue-next'

const props = defineProps({
  isStreaming: { type: Boolean, default: false },
})

const emit = defineEmits(['send', 'abort'])

const message = ref('')
const textareaRef = ref(null)

function handleSend() {
  const text = message.value.trim()
  if (!text || props.isStreaming) return
  emit('send', text)
  message.value = ''
  nextTick(() => adjustHeight())
}

function handleKeydown(e) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  }
}

function adjustHeight() {
  const el = textareaRef.value
  if (!el) return
  el.style.height = 'auto'
  el.style.height = Math.min(el.scrollHeight, 128) + 'px'
}
</script>

<template>
  <div class="px-6 py-4 border-t border-gray-100">
    <form @submit.prevent="handleSend" class="flex items-end gap-3">
      <textarea
        ref="textareaRef"
        v-model="message"
        @keydown="handleKeydown"
        @input="adjustHeight"
        placeholder="输入你的问题... (Shift+Enter 换行)"
        rows="1"
        class="flex-1 px-4 py-2.5 border border-gray-200 rounded-xl text-sm resize-none focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent overflow-y-auto"
        style="max-height: 128px"
      />
      <button
        v-if="isStreaming"
        @click="emit('abort')"
        type="button"
        class="p-2.5 bg-red-500 text-white rounded-xl hover:bg-red-600 transition-colors"
      >
        <Square class="w-5 h-5" />
      </button>
      <button
        v-else
        type="submit"
        :disabled="!message.trim()"
        class="p-2.5 bg-brand-600 text-white rounded-xl hover:bg-brand-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
      >
        <Send class="w-5 h-5" />
      </button>
    </form>
    <p class="text-xs text-gray-400 mt-2 text-center">
      按 Enter 发送，Shift+Enter 换行。系统会自动识别你的学习意图并调用对应的智能体。
    </p>
  </div>
</template>
